spring.application.name=blogadminservice
server.port=8081

spring.data.mongodb.uri=mongodb+srv://rockasking08_db_user:xny5CpNQkIW9NlIx@blogwebsite.khfg9sf.mongodb.net/?appName=blogwebsite
#mongodb+srv://<db_username>:<db_password>@blogwebsite.khfg9sf.mongodb.net/?appName=blogwebsite
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
#AIzaSyDymDhBiIvEihOP78aK3XU9xp3qBrQc5UQ -- api key

#AIzaSyDNCbUnygKKtvTCsP3TAnzD_02oh8gjuTY  -- new api key



#49.206.208.69