spring.application.name=blog-content-service
server.port=8082


spring.data.mongodb.uri=mongodb+srv://<user>:<pass>@cluster.mongodb.net/blogdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
